import 'package:flutter/material.dart';
import 'package:pet_shop_ui/models/category.dart';
import 'package:pet_shop_ui/models/pet.dart';
List<PetCategory> categories = [
  PetCategory(
    name: "Cats",
    pets: [
      Pet(
        name: "Fluffy",
        pet_image: "assets/cat1.png",
        bg_color: Colors.orange,
        age: 2,
        weight: 4.5,
        description: "Fluffy is a playful and friendly cat.",
      ),
      Pet(
        name: "Whiskers",
        pet_image: "assets/cat2.png",
        bg_color: Colors.blue,
        age: 3,
        weight: 5.2,
        description: "Whiskers loves to explore and cuddle.",
      ),
      Pet(
        name: "Mittens",
        pet_image: "assets/cat3.png",
        bg_color: Colors.yellow,
        age: 1,
        weight: 3.8,
        description: "Mittens is a curious and energetic kitten.",
      ),
      Pet(
        name: "Salem",
        pet_image: "assets/cat4.png",
        bg_color: Colors.grey,
        age: 4,
        weight: 6.0,
        description: "Salem is a calm and independent cat.",
      ),
      Pet(
        name: "Oscar",
        pet_image: "assets/cat3.png",
        bg_color: Colors.brown,
        age: 5,
        weight: 5.5,
        description: "Oscar loves to play fetch and take naps.",
      ),
    ],
  ),
  PetCategory(
    name: "Dogs",
    pets: [
      Pet(
        name: "Buddy",
        pet_image: "assets/dog1.png",
        bg_color: Colors.green,
        age: 3,
        weight: 15.0,
        description: "Buddy is a loyal and friendly dog.",
      ),
      Pet(
        name: "Max",
        pet_image: "assets/dog1.png",
        bg_color: Colors.purple,
        age: 2,
        weight: 12.5,
        description: "Max enjoys long walks and playing fetch.",
      ),
      Pet(
        name: "Charlie",
        pet_image: "assets/dog1.png",
        bg_color: Colors.red,
        age: 4,
        weight: 14.0,
        description: "Charlie is an energetic and loving dog.",
      ),
      Pet(
        name: "Lucy",
        pet_image: "assets/dog1.png",
        bg_color: Colors.teal,
        age: 5,
        weight: 11.8,
        description: "Lucy loves belly rubs and car rides.",
      ),
      Pet(
        name: "Rocky",
        pet_image: "assets/dog1.png",
        bg_color: Colors.indigo,
        age: 6,
        weight: 18.2,
        description: "Rocky is a brave and playful dog.",
      ),
    ],
  ),
  PetCategory(
    name: "Birds",
    pets: [
      Pet(
        name: "Kiwi",
        pet_image: "assets/bird1.png",
        bg_color: Colors.yellow,
        age: 1,
        weight: 0.5,
        description: "Kiwi is a colorful and chirpy bird.",
      ),
      Pet(
        name: "Pepper",
        pet_image: "assets/bird2.png",
        bg_color: Colors.green,
        age: 2,
        weight: 0.8,
        description: "Pepper loves to mimic sounds and talk.",
      ),
      Pet(
        name: "Sunny",
        pet_image: "assets/bird3.png",
        bg_color: Colors.orange,
        age: 3,
        weight: 0.6,
        description: "Sunny enjoys flying and exploring new places.",
      ),
      Pet(
        name: "Ruby",
        pet_image: "assets/bird4.png",
        bg_color: Colors.red,
        age: 2,
        weight: 0.7,
        description: "Ruby is a sweet and sociable bird.",
      ),
      Pet(
        name: "Sky",
        pet_image: "assets/bird2.png",
        bg_color: Colors.blue,
        age: 1,
        weight: 0.6,
        description: "Sky loves to perch and observe its surroundings.",
      ),
    ],
  ),
  PetCategory(
    name: "Fish",
    pets: [
      Pet(
        name: "Nemo",
        pet_image: "assets/bird3.png",
        bg_color: Colors.orange,
        age: 1,
        weight: 0.2,
        description: "Nemo is a colorful and playful fish.",
      ),
      Pet(
        name: "Bubbles",
        pet_image: "assets/dog1.png",
        bg_color: Colors.blue,
        age: 2,
        weight: 0.3,
        description: "Bubbles enjoys swimming and exploring the tank.",
      ),
      Pet(
        name: "Finley",
        pet_image: "assets/cat4.png",
        bg_color: Colors.green,
        age: 1,
        weight: 0.25,
        description: "Finley is a curious and graceful fish.",
      ),
      Pet(
        name: "Goldie",
        pet_image: "assets/bird4.png",
        bg_color: Colors.yellow,
        age: 2,
        weight: 0.3,
        description: "Goldie is a friendly and bright fish.",
      ),
      Pet(
        name: "Splash",
        pet_image: "assets/bird2.png",
        bg_color: Colors.cyan,
        age: 1,
        weight: 0.2,
        description: "Splash loves to play in the water and show off its colors.",
      ),
    ],
  ),
];
